-- MySQL Script generated by MySQL Workbench
-- Wed Dec 21 02:14:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema transporte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transporte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transporte` DEFAULT CHARACTER SET utf8 ;
USE `transporte` ;

-- -----------------------------------------------------
-- Table `transporte`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idlogin`),
  UNIQUE INDEX `usuario` (`usuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `transporte`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`motorista` (
  `idmotorista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `idade` VARCHAR(45) NULL DEFAULT NULL,
  `dtnasc` DATETIME NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `enderecorua` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmotorista`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `transporte`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`viagem` (
  `idviagem` INT NOT NULL AUTO_INCREMENT,
  `id_motorista` INT NOT NULL,
  `partida` VARCHAR(45) NULL DEFAULT NULL,
  `destino` VARCHAR(45) NULL DEFAULT NULL,
  `dataviagem` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`idviagem`),
  INDEX `id_motorista_idx` (`id_motorista` ASC),
  CONSTRAINT `idmotorista`
    FOREIGN KEY (`id_motorista`)
    REFERENCES `transporte`.`motorista` (`idmotorista`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
